# NANDA SHEPTIANA 2009106096
## POSTTEST 7 TENSORFLOW
## KB B2 2020

In [2]:
import tensorflow as tf

### Tensor Random

In [22]:
random_tensor = tf.random.normal([5,5], mean = 0, stddev = 1.0, seed = 1)

In [23]:
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8779576 ,  0.30241513,  0.69269043, -0.03312119,  0.15334924],
       [-0.05293268, -0.42697585, -0.74988204, -1.248371  ,  0.8057842 ],
       [-0.6682823 ,  0.4097648 ,  0.8608653 ,  0.8790354 ,  1.2187856 ],
       [ 0.4769576 ,  0.09455841, -0.12560269, -1.0556796 , -0.5452273 ],
       [ 0.81807566, -0.27364784,  0.37316537,  0.5857222 ,  0.26029605]],
      dtype=float32)>

### List Tensor (tf.convert_to_tensor)

In [68]:
list_prime = [[2, 3, 5, 7, 11], 
              [13, 17, 19, 23, 29], 
              [31, 37, 41, 43, 47], 
              [53, 59, 61, 71, 73], 
              [79, 83, 89, 97, 101]]

prime_tensor = tf.convert_to_tensor(list_prime, dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Dimension Display

In [69]:
# dimension display random
print("Dimensi display Random : ")
print(random_tensor.shape)
print(random_tensor.get_shape())
print(tf.shape(random_tensor))

print()

# dimension display prime
print("Dimensi display Prime : ")
print(prime_tensor.shape)
print(prime_tensor.get_shape())
print(tf.shape(prime_tensor))

Dimensi display Random : 
(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)

Dimensi display Prime : 
(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)


### Dimension Reshaping

In [70]:
# dimension reshaping random
print("Dimensi Reshaping Random : ")
tf.reshape(random_tensor, (5,5))

Dimensi Reshaping Random : 


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8779576 ,  0.30241513,  0.69269043, -0.03312119,  0.15334924],
       [-0.05293268, -0.42697585, -0.74988204, -1.248371  ,  0.8057842 ],
       [-0.6682823 ,  0.4097648 ,  0.8608653 ,  0.8790354 ,  1.2187856 ],
       [ 0.4769576 ,  0.09455841, -0.12560269, -1.0556796 , -0.5452273 ],
       [ 0.81807566, -0.27364784,  0.37316537,  0.5857222 ,  0.26029605]],
      dtype=float32)>

In [71]:
# dimension reshaping prime
print("Dimensi Reshaping Random : ")
tf.reshape(prime_tensor, (5,5))

Dimensi Reshaping Random : 


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Dimension Expansion

In [72]:
# dimension expansion random
expand_random = tf.expand_dims(random_tensor, axis = 1)
print("Dimensi Expansion Random : ", expand_random.shape)

# dimension expansion prime
expand_prime = tf.expand_dims(prime_tensor, axis = 0)
print("Dimensi Expansion Prime : ", expand_prime.shape)

Dimensi Expansion Random :  (5, 1, 5)
Dimensi Expansion Prime :  (1, 5, 5)


### Dimension Squeezing

In [73]:
# dimension squeezing random
squeeze_random = tf.squeeze(random_tensor)
print("Dimensi Squeezing Random : ", squeeze_random.shape)

# dimension squeezing prime
squeeze_prime = tf.squeeze(prime_tensor)
print("Dimensi Squeezing Prime : ", squeeze_prime.shape)

Dimensi Squeezing Random :  (5, 5)
Dimensi Squeezing Prime :  (5, 5)


### Operasi Aritmatika

#### Arithmetic Operators

In [77]:
# Penjumlahan
tf.add(random_tensor, prime_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.1220424,   3.3024151,   5.6926904,   6.966879 ,  11.153349 ],
       [ 12.947067 ,  16.573025 ,  18.250118 ,  21.751629 ,  29.805784 ],
       [ 30.331718 ,  37.409763 ,  41.860867 ,  43.879036 ,  48.218784 ],
       [ 53.47696  ,  59.09456  ,  60.874397 ,  69.94432  ,  72.45477  ],
       [ 79.81808  ,  82.72635  ,  89.37317  ,  97.585724 , 101.2603   ]],
      dtype=float32)>

In [78]:
# Pengurangan
tf.subtract(random_tensor, prime_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -2.8779576,   -2.6975849,   -4.3073096,   -7.033121 ,
         -10.846651 ],
       [ -13.052933 ,  -17.426975 ,  -19.749882 ,  -24.248371 ,
         -28.194216 ],
       [ -31.668282 ,  -36.590237 ,  -40.139133 ,  -42.120964 ,
         -45.781216 ],
       [ -52.52304  ,  -58.90544  ,  -61.125603 ,  -72.05568  ,
         -73.54523  ],
       [ -78.18192  ,  -83.27365  ,  -88.62683  ,  -96.414276 ,
        -100.7397   ]], dtype=float32)>

In [79]:
# Perkalian
tf.multiply(random_tensor, prime_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.7559152 ,   0.9072454 ,   3.463452  ,  -0.23184831,
          1.6868416 ],
       [ -0.6881248 ,  -7.2585893 , -14.247759  , -28.712534  ,
         23.367743  ],
       [-20.716751  ,  15.161298  ,  35.29548   ,  37.798523  ,
         57.282925  ],
       [ 25.278751  ,   5.578946  ,  -7.661764  , -74.95325   ,
        -39.801594  ],
       [ 64.627975  , -22.71277   ,  33.21172   ,  56.815056  ,
         26.2899    ]], dtype=float32)>

In [80]:
# Pembagian
tf.divide(random_tensor, prime_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.4389788 ,  0.10080504,  0.13853809, -0.0047316 ,  0.01394084],
       [-0.00407174, -0.02511623, -0.03946748, -0.054277  ,  0.02778566],
       [-0.02155749,  0.01107472,  0.02099671,  0.02044268,  0.02593161],
       [ 0.0089992 ,  0.00160268, -0.00205906, -0.01486873, -0.00746887],
       [ 0.01035539, -0.00329696,  0.00419287,  0.00603837,  0.00257719]],
      dtype=float32)>

In [84]:
# Logaritma random
tf.math.log(random_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[        nan, -1.1959546 , -0.3671721 ,         nan, -1.8750374 ],
       [        nan,         nan,         nan,         nan, -0.21593928],
       [        nan, -0.8921719 , -0.14981723, -0.12893009,  0.19785498],
       [-0.7403277 , -2.3585374 ,         nan,         nan,         nan],
       [-0.20080043,         nan, -0.9857336 , -0.53490967, -1.3459357 ]],
      dtype=float32)>

In [85]:
# Logaritma prime
tf.math.log(prime_tensor).numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.6931472, 1.0986123, 1.609438 , 1.9459102, 2.3978953],
       [2.5649493, 2.8332133, 2.944439 , 3.1354942, 3.3672957],
       [3.4339871, 3.610918 , 3.713572 , 3.7612002, 3.8501477],
       [3.9702919, 4.0775375, 4.1108737, 4.26268  , 4.2904596],
       [4.3694477, 4.4188404, 4.4886365, 4.574711 , 4.6151204]],
      dtype=float32)>

In [91]:
# Pangkat
tf.pow(random_tensor, prime_tensor).numpy()

array([[ 7.7080953e-01,  2.7657349e-02,  1.5947622e-01, -4.3726155e-11,
         1.1028026e-09],
       [-2.5610028e-17, -5.2102223e-07, -4.2156652e-03, -1.6440102e+02,
         1.9069710e-03],
       [-3.7476423e-06,  4.6108590e-15,  2.1495284e-03,  3.9108754e-03,
         1.0929103e+04],
       [ 9.1080932e-18,  0.0000000e+00, -0.0000000e+00, -4.6857597e+01,
        -5.8906562e-20],
       [ 1.2902804e-07, -0.0000000e+00,  0.0000000e+00,  2.9247854e-23,
         0.0000000e+00]], dtype=float32)

#### Matrix Multiplication

In [86]:
tf.matmul(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  34.008053,   38.91057 ,   41.384094,   43.118805,   44.73938 ],
       [ -31.409605,  -41.93683 ,  -43.558205,  -52.909164,  -57.955894],
       [ 173.55016 ,  189.83546 ,  201.83267 ,  222.39755 ,  232.25967 ],
       [-100.73448 , -109.147896, -113.89    , -127.72766 , -130.04716 ],
       [  61.25352 ,   67.771515,   73.08625 ,   82.313736,   87.64944 ]],
      dtype=float32)>

### Nilai Maksimal & Minimum

#### Tensor Statistics Collection

In [95]:
# Statistic argmax random (maksimal)
tf.argmax(random_tensor, axis = 1).numpy()

array([2, 4, 4, 0, 0], dtype=int64)

In [96]:
# Statistic argmax prime (maksimal)
tf.argmax(prime_tensor, axis = 1).numpy()

array([4, 4, 4, 4, 4], dtype=int64)

In [97]:
# Statistic argmin random (minimal)
tf.argmin(random_tensor, axis = 1).numpy()

array([0, 3, 0, 3, 1], dtype=int64)

In [98]:
# Statistic argmin prime (minimal)
tf.argmin(prime_tensor, axis = 1).numpy()

array([0, 0, 0, 0, 0], dtype=int64)

### Penggabungan (Tensor Concatenation)

In [100]:
# tf.concat()
concat = tf.concat([random_tensor, prime_tensor], axis = 0)
print(concat.shape)
print(concat)

(10, 5)
tf.Tensor(
[[-8.7795758e-01  3.0241513e-01  6.9269043e-01 -3.3121187e-02
   1.5334924e-01]
 [-5.2932676e-02 -4.2697585e-01 -7.4988204e-01 -1.2483710e+00
   8.0578423e-01]
 [-6.6828227e-01  4.0976480e-01  8.6086529e-01  8.7903541e-01
   1.2187856e+00]
 [ 4.7695759e-01  9.4558410e-02 -1.2560269e-01 -1.0556796e+00
  -5.4522729e-01]
 [ 8.1807566e-01 -2.7364784e-01  3.7316537e-01  5.8572221e-01
   2.6029605e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  7.1000000e+01
   7.3000000e+01]
 [ 7.9000000e+01  8.3000000e+01  8.9000000e+01  9.7000000e+01
   1.0100000e+02]], shape=(10, 5), dtype=float32)


In [101]:
# tf.stack()
stack = tf.stack([random_tensor, prime_tensor], axis = 0)
print(stack.shape)
print(stack)

(2, 5, 5)
tf.Tensor(
[[[-8.7795758e-01  3.0241513e-01  6.9269043e-01 -3.3121187e-02
    1.5334924e-01]
  [-5.2932676e-02 -4.2697585e-01 -7.4988204e-01 -1.2483710e+00
    8.0578423e-01]
  [-6.6828227e-01  4.0976480e-01  8.6086529e-01  8.7903541e-01
    1.2187856e+00]
  [ 4.7695759e-01  9.4558410e-02 -1.2560269e-01 -1.0556796e+00
   -5.4522729e-01]
  [ 8.1807566e-01 -2.7364784e-01  3.7316537e-01  5.8572221e-01
    2.6029605e-01]]

 [[ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
    1.1000000e+01]
  [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
    2.9000000e+01]
  [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
    4.7000000e+01]
  [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  7.1000000e+01
    7.3000000e+01]
  [ 7.9000000e+01  8.3000000e+01  8.9000000e+01  9.7000000e+01
    1.0100000e+02]]], shape=(2, 5, 5), dtype=float32)


### Sorting

In [104]:
# sort concat
tf.sort(concat, direction="DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 6.9269043e-01,  3.0241513e-01,  1.5334924e-01, -3.3121187e-02,
        -8.7795758e-01],
       [ 8.0578423e-01, -5.2932676e-02, -4.2697585e-01, -7.4988204e-01,
        -1.2483710e+00],
       [ 1.2187856e+00,  8.7903541e-01,  8.6086529e-01,  4.0976480e-01,
        -6.6828227e-01],
       [ 4.7695759e-01,  9.4558410e-02, -1.2560269e-01, -5.4522729e-01,
        -1.0556796e+00],
       [ 8.1807566e-01,  5.8572221e-01,  3.7316537e-01,  2.6029605e-01,
        -2.7364784e-01],
       [ 1.1000000e+01,  7.0000000e+00,  5.0000000e+00,  3.0000000e+00,
         2.0000000e+00],
       [ 2.9000000e+01,  2.3000000e+01,  1.9000000e+01,  1.7000000e+01,
         1.3000000e+01],
       [ 4.7000000e+01,  4.3000000e+01,  4.1000000e+01,  3.7000000e+01,
         3.1000000e+01],
       [ 7.3000000e+01,  7.1000000e+01,  6.1000000e+01,  5.9000000e+01,
         5.3000000e+01],
       [ 1.0100000e+02,  9.7000000e+01,  8.9000000e+01,  8.3000000e+01,
      

In [105]:
# argsort concat
tf.argsort(concat, direction="DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[2, 1, 4, 3, 0],
       [4, 0, 1, 2, 3],
       [4, 3, 2, 1, 0],
       [0, 1, 2, 4, 3],
       [0, 3, 2, 4, 1],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])>

In [106]:
# sort stack
tf.sort(stack, direction="DESCENDING")

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[ 6.9269043e-01,  3.0241513e-01,  1.5334924e-01, -3.3121187e-02,
         -8.7795758e-01],
        [ 8.0578423e-01, -5.2932676e-02, -4.2697585e-01, -7.4988204e-01,
         -1.2483710e+00],
        [ 1.2187856e+00,  8.7903541e-01,  8.6086529e-01,  4.0976480e-01,
         -6.6828227e-01],
        [ 4.7695759e-01,  9.4558410e-02, -1.2560269e-01, -5.4522729e-01,
         -1.0556796e+00],
        [ 8.1807566e-01,  5.8572221e-01,  3.7316537e-01,  2.6029605e-01,
         -2.7364784e-01]],

       [[ 1.1000000e+01,  7.0000000e+00,  5.0000000e+00,  3.0000000e+00,
          2.0000000e+00],
        [ 2.9000000e+01,  2.3000000e+01,  1.9000000e+01,  1.7000000e+01,
          1.3000000e+01],
        [ 4.7000000e+01,  4.3000000e+01,  4.1000000e+01,  3.7000000e+01,
          3.1000000e+01],
        [ 7.3000000e+01,  7.1000000e+01,  6.1000000e+01,  5.9000000e+01,
          5.3000000e+01],
        [ 1.0100000e+02,  9.7000000e+01,  8.9000000e+01,

In [107]:
# argsort stack
tf.argsort(stack, direction="DESCENDING")

<tf.Tensor: shape=(2, 5, 5), dtype=int32, numpy=
array([[[2, 1, 4, 3, 0],
        [4, 0, 1, 2, 3],
        [4, 3, 2, 1, 0],
        [0, 1, 2, 4, 3],
        [0, 3, 2, 4, 1]],

       [[4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0]]])>